app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.Home.as_view(), name='home')
]

fibonacci/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls',namespace='app'))
]

app/models.py
from django.db import models


# Create your models here.
class Fibonacci(models.Model):
    number = models.TextField()
    fib_value = models.TextField()

    def __str__(self):
        return self.number

app/views.py
import time

from django.shortcuts import render
from django.views.generic.base import View

from .models import Fibonacci
from .utils import fibonacci_nth, MatrixFibonacci
from datetime import timedelta

from django.core.cache import cache


# Create your views here.

class Home(View):
    template_name = 'app/index.html'

    def get(self, request, *args, **kwargs):
        context={}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        start = time.time()

        context = {}
        n=request.POST['fibonacci_number']
        key=str(n)
        if int(n) > 0:
            context['fibonacci_number']=n
            if cache.get(key):
                data = cache.get(key)
                context['fibonacci_value'] = data
                context['message'] = 'Fetched value from cache'


            elif Fibonacci.objects.filter(number=n).exists():
                obj = Fibonacci.objects.get(number=n)
                value = obj.fib_value
                context['fibonacci_value'] = value
                #time_taken_direct='0'
                #time_taken_mat='0'
                cache.set(key, str(value))
                context['message'] = 'Fetched value from database'

            else:
                # start_d = time.time()
                # fibonacci_nth(int(n))
                # time_taken_direct=str(timedelta(seconds=time.time()-start_d))
                start_m = time.time()
                mf=MatrixFibonacci()
                ans=mf.get_number(int(n))
                time_taken_mat = str(timedelta(seconds=time.time() - start_m))
                context['fibonacci_value'] = ans
                data = Fibonacci(number=n, fib_value=ans)
                data.save()
                cache.set(key, str(ans))
                context['message'] = 'Calculated from function'
                context['time_taken_mat'] = time_taken_mat
        else:
            context['message1'] = 'Enter postive number only'
        end = time.time()
        time_taken=str(timedelta(seconds=end-start))
        context['total_time_taken']=time_taken
        #context['time_taken_direct'] = time_taken_direct


        return render(request, self.template_name, context)

app/templates/app/base.html
{% load static %}
<html>
    <head>
        {% load static %}
        <title>Fibonacci App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script src="{% static 'js/app.js' %}"></script>

    </head>
    <body>
    <div class="container">
        <div class="page-header">
        <h1><a href={% url 'app:home' %}>Fibonacci App</a></h1>
        </div>

            {% block content %}
            {% endblock %}
    </div>

    {% block extra_js %}

    {% endblock extra_js %}
</body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
   <form class="form-horizontal" method="POST">
       {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-6">
                <input type="number" class="form-control" name="fibonacci_number" placeholder="Enter number" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4">
                <button class="btn btn-primary col-sm-4" type="submit">Find</button>
            </div>
        </div>
    </form>


<!--{% if time_taken_direct %}-->
<!--<h4>Time Taken Direct Method: {{ time_taken_direct }}</h4>-->
<!--{% endif %}-->
{% if message1 %}
    <div class="alert alert-danger col-sm-8">
        {{ message1 }}
    </div>
{% endif %}
{% if message %}
    <div class="alert alert-success col-sm-8">
      {{ message }}
        <br>
        {% if total_time_taken %}
            Total Time Taken : {{ total_time_taken }}
        <br>
        {% endif %}
        {% if time_taken_mat %}
            Time Taken Compute Matrix Multiplication: {{ time_taken_mat }}
        {% endif %}
    </div>

{% endif %}




{% if fibonacci_value and fibonacci_number %}

    <div class="alert alert-info col-sm-8">
        <div>

                {% with a=fibonacci_number %}
                    {% if a == '1' %}
                         1<sup>st</sup> term of Fibonacci series
                    {% elif a == '2' %}
                         2<sup>nd</sup> term of Fibonacci series
                    {% elif a == '3' %}
                         3<sup>rd</sup> term of Fibonacci series
                    {% else %}
                         {{ a }}<sup>th</sup> term of Fibonacci series
                    {% endif %}

                {% endwith %}

            <button class="btn btn-outline-info btn-sm" script="float: right;" onclick="copyFunction()">Copy text</button>
        </div>

          <h5 style="word-wrap: break-word;" id="fibonacci_value">{{ fibonacci_value }}</h5>
    </div>
{% endif %}

{% endblock content %}

{% block extra_js %}

{% endblock extra_js%}